name: $(versionNumber)

trigger:
- master

resources:
- repo: self

variables:
  version: '$(versionNumber)'
  clientAppFolder: 'client-app'
  apiFolder: 'api'
  imageRepository: 'wasoft'
  dockerfilePath: '$(clientAppFolder)/Dockerfile'
  tag: '$(versionNumber)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: ClientApp
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: FileTransform@1
      displayName: 'Update package.json'
      inputs:
        folderPath: '$(clientAppFolder)'
        targetFiles: '**/package.json'
        fileType: json
    - task: Docker@2
      displayName: 'Login to Container Registry'
      inputs:
        command: login
        containerRegistry: 'gcr-wasoft'
    - task: Docker@2
      displayName: 'Build and push image'
      inputs:
        Dockerfile: '$(dockerfilePath)'
        command: buildAndPush
        repository: '$(imageRepository)'
        tags: |
          $(tag)
