name: $(versionNumber)

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: ApiJob
  displayName: Build API

  variables:
    buildConfiguration: 'Release'
    apiFolder: 'api'

  steps:
    - task: Assembly-Info-NetCore@3
      inputs:
        Path: '$(apiFolder)'
        FileNames: '**/*.csproj'
        InsertAttributes: false
        FileEncoding: 'auto'
        WriteBOM: false
        PackageId: '$(versionNumber)'
        Authors: 'Paweł Wawrzynek'
        Company: 'WaSoft'
        Product: 'WaSoft API'
        Copyright: 'WaSoft'
        VersionNumber: '$(versionNumber)'
        FileVersionNumber: '$(versionNumber)'
        InformationalVersion: '$(versionNumber)'
        PackageVersion: '$(versionNumber)'
        LogLevel: 'verbose'
        FailOnWarning: false
        DisableTelemetry: false

    - task: UseDotNet@2
      displayName: 'Use dotnet 6'
      inputs:
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(apiFolder)/*.sln'
      displayName: 'Restore NuGet packages'
 
    - task: DotNetCoreCLI@2
      displayName: 'Build the solution'
      inputs:
        command: 'build'
        projects: '$(apiFolder)/*.sln'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: test
        projects: '$(apiFolder)/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Create publish package'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(apiFolder)/*.sln'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: Publish package
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'wasoft-api'
     
- job: AppJob
  displayName: Build Client App

  variables:
    clientAppFolder: 'client-app'
    buildOutputFolder: '$(clientAppFolder)/build'
    configFilename: 'appConfig'
    version: '$(versionNumber)'

  steps:
    - task: CMdLine@2
      displayName: 'Replace config files'
      inputs:
        script: |
          pushd $(clientAppFolder)/public
          mv $(configFilename).release.js $(configFilename).js
          popd

    - task: FileTransform@1
      displayName: 'Update package.json'
      inputs:
        folderPath: '$(clientAppFolder)'
        targetFiles: '**/package.json'
        fileType: json

    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '16.x'

    - script: |
        pushd $(clientAppFolder) && npm install && popd
        pushd $(clientAppFolder) && npm run build && popd
      displayName: 'npm install and build'

    - task: CopyFiles@2
      displayName: 'Copy to the staging directory'
      inputs:
        sourceFolder: '$(buildOutputFolder)' 
        contents: '**/*' 
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true

    - task: ArchiveFiles@2
      displayName: 'Archive into zip file for publishing'
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        includeRootFolder: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publish package'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifactName: 'wasoft-app'