# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 2.0$(Rev:.r)-pr

trigger: none
pr:
  branches:
    include:
    - develop
    exclude:
    - feature/*
  paths:
    include:
    - api
    exclude:
    - '**/*.yml'
    - '**/*.md'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectFolder: 'api'

steps:
- task: Assembly-Info-NetCore@2
  displayName: 'Update assembly info'
  inputs:
    Path: '$(projectFolder)'
    FileNames: '**/*.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    PackageId: '$(Build.BuildNumber)'
    Authors: 'Paweł Wawrzynek'
    Company: 'WaSoft'
    Product: 'WaSoft API'
    Copyright: 'WaSoft'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build'
    projects: '$(projectFolder)/WaSoft.Api.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '$(projectFolder)/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'